"""meter

Revision ID: e0f885133da6
Revises: 660d0bbffc26
Create Date: 2021-10-29 08:41:04.135889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0f885133da6"
down_revision = "660d0bbffc26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blood_glucose_meter",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("mobile_id", sa.String(length=36), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("patient_id", sa.String(), nullable=False),
        sa.Column("date_verified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_bg_value_correct", sa.Boolean(), nullable=True),
        sa.Column("app_product", sa.String(), nullable=False),
        sa.Column("app_version", sa.String(), nullable=False),
        sa.Column("blood_glucose_value", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blood_glucose_meter")
    # ### end Alembic commands ###
