@startuml

skinparam defaultFontName Courier

Class BloodGlucoseMeter {
    VARCHAR[36] ★ uuid               
    VARCHAR     ⚪ app_product        
    VARCHAR     ⚪ app_version        
    FLOAT       ⚪ blood_glucose_value
    DATETIME    ⚪ created            
    VARCHAR     ⚪ created_by_        
    DATETIME    ⚪ date_verified      
    BOOLEAN     ⚪ is_bg_value_correct
    VARCHAR[36] ⚪ mobile_id          
    DATETIME    ⚪ modified           
    VARCHAR     ⚪ modified_by_       
    VARCHAR[36] ⚪ patient_id         
    VARCHAR     ⚪ serial_number      
    to_dict()                        
}

Class Desktop {
    VARCHAR[36] ★ uuid                      
    VARCHAR     ⚪ app_product               
    VARCHAR     ⚪ app_version               
    VARCHAR[36] ⚪ clinician_id              
    DATETIME    ⚪ created                   
    VARCHAR     ⚪ created_by_               
    DATETIME    ⚪ date_first_used_          
    INTEGER     ⚪ date_first_used_time_zone_
    VARCHAR     ⚪ desktop_os                
    VARCHAR     ⚪ desktop_os_version        
    VARCHAR     ⚪ ip_address                
    DATETIME    ⚪ modified                  
    VARCHAR     ⚪ modified_by_              
    VARCHAR     ⚪ unique_device_code        
    to_dict()                               
}

Class Mobile {
    VARCHAR[36] ★ uuid                          
    VARCHAR     ⚪ app_product                   
    VARCHAR     ⚪ app_version                   
    DATETIME    ⚪ created                       
    VARCHAR     ⚪ created_by_                   
    DATETIME    ⚪ date_first_launched_          
    INTEGER     ⚪ date_first_launched_time_zone_
    VARCHAR     ⚪ display_name                  
    VARCHAR     ⚪ manufacturer                  
    VARCHAR     ⚪ model                         
    DATETIME    ⚪ modified                      
    VARCHAR     ⚪ modified_by_                  
    VARCHAR[36] ⚪ patient_id                    
    VARCHAR     ⚪ phone_os                      
    VARCHAR     ⚪ phone_os_version              
    VARCHAR     ⚪ unique_device_code            
    to_dict()                                   
}

right footer generated by sadisplay v0.4.9

@enduml
